Repository Monolong/2024_Hackathon_Game, pull requests merged in 2024-08, with the labels that each got.

#10 Create Object Pool Manager
  Assets/ObjectPool.meta
  Assets/ObjectPool/Script.meta
  Assets/ObjectPool/Script/ObjPoolManager.cs
  Assets/ObjectPool/Script/ObjPoolManager.cs.meta
  Assets/Scenes/SampleScene.unity
Labels: enhancement

#12 Enhancement/3
  Assets/Image.meta
  Assets/Image/KakaoTalk_20240813_214212961.jpg
  Assets/Image/KakaoTalk_20240813_214212961.jpg.meta
  Assets/Image/KakaoTalk_20240813_214212961_01.jpg
  Assets/Image/KakaoTalk_20240813_214212961_01.jpg.meta
  Assets/Image/KakaoTalk_20240813_220936451.jpg
  Assets/Image/KakaoTalk_20240813_220936451.jpg.meta
  Assets/Image/KakaoTalk_20240813_220936451_01.jpg
  Assets/Image/KakaoTalk_20240813_220936451_01.jpg.meta
  Assets/Image/KakaoTalk_20240813_220936451_02.jpg
  Assets/Image/KakaoTalk_20240813_220936451_02.jpg.meta
  Assets/Scenes/Map.unity
  Assets/Scenes/Map.unity.meta
  Assets/Scenes/TestScene.unity
  Assets/Scenes/TestScene.unity.meta
  Assets/Tile.meta
  Assets/Tile/KakaoTalk_20240813_214212961.asset
  Assets/Tile/KakaoTalk_20240813_214212961.asset.meta
  Assets/Tile/KakaoTalk_20240813_214212961_01.asset
  Assets/Tile/KakaoTalk_20240813_214212961_01.asset.meta
  Assets/Tile/KakaoTalk_20240813_220936451.asset
  Assets/Tile/KakaoTalk_20240813_220936451.asset.meta
  Assets/Tile/KakaoTalk_20240813_220936451_01.asset
  Assets/Tile/KakaoTalk_20240813_220936451_01.asset.meta
  Assets/Tile/KakaoTalk_20240813_220936451_02.asset
  Assets/Tile/KakaoTalk_20240813_220936451_02.asset.meta
  Assets/Tilemap.meta
  Assets/Tilemap/Road.prefab
  Assets/Tilemap/Road.prefab.meta
  Assets/Tilemap/Sidewalk.prefab
  Assets/Tilemap/Sidewalk.prefab.meta
Labels: enhancement

#15 Enhancement/5
  Assets/KMC/Prefebs.meta
  Assets/KMC/Prefebs/Station.prefab
  Assets/KMC/Prefebs/Station.prefab.meta
  Assets/KMC/Scenes/Station.unity
  Assets/KMC/Scripts/Station.cs
  ProjectSettings/TagManager.asset
Labels: duplicate

#21 Enhancement/7
  Assets/Node.meta
  Assets/Node/DummyCodes.cs
  Assets/Node/DummyCodes.cs.meta
  Assets/Node/Node.cs
  Assets/Node/Node.cs.meta
  Assets/Node/Prefab.meta
  Assets/Node/Prefab/Citizen.prefab
  Assets/Node/Prefab/Citizen.prefab.meta
  Assets/Node/Sprite.meta
  Assets/Node/Sprite/Citizen.png
  Assets/Node/Sprite/Citizen.png.meta
  Assets/Node/Sprite/Factory.png
  Assets/Node/Sprite/Factory.png.meta
  Assets/Node/Sprite/Home.png
  Assets/Node/Sprite/Home.png.meta
  Assets/Scenes/NodeSampleScene.unity
  Assets/Scenes/NodeSampleScene.unity.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#24 enhancement/23
  Assets/JJW/Image/Building.meta
  Assets/JJW/Image/Building/KakaoTalk_20240814_032124264_01.png
  Assets/JJW/Image/Building/KakaoTalk_20240814_032124264_01.png.meta
  Assets/JJW/Image/Building/KakaoTalk_20240814_032124264_02.png
  Assets/JJW/Image/Building/KakaoTalk_20240814_032124264_02.png.meta
  Assets/JJW/Image/Building/KakaoTalk_20240814_032124264_03.png
  Assets/JJW/Image/Building/KakaoTalk_20240814_032124264_03.png.meta
  Assets/JJW/Image/Building/KakaoTalk_20240814_032124264_04.png
  Assets/JJW/Image/Building/KakaoTalk_20240814_032124264_04.png.meta
  Assets/JJW/Image/Icon.meta
  Assets/JJW/Image/Icon/KakaoTalk_20240814_032124264_05.png
  Assets/JJW/Image/Icon/KakaoTalk_20240814_032124264_05.png.meta
  Assets/JJW/Image/Icon/KakaoTalk_20240814_032124264_06.png
  Assets/JJW/Image/Icon/KakaoTalk_20240814_032124264_06.png.meta
  Assets/JJW/Image/Icon/KakaoTalk_20240814_032124264_07.png
  Assets/JJW/Image/Icon/KakaoTalk_20240814_032124264_07.png.meta
  Assets/JJW/Image/KakaoTalk_20240814_032124264.png
  Assets/JJW/Image/KakaoTalk_20240814_032124264.png.meta
  Assets/Scenes.meta
Labels: enhancement

#20 Enhancement/4
  Assets/HIS.meta
  Assets/HIS/Prefab.meta
  Assets/HIS/Script.meta
  Assets/HIS/Script/Citizen.cs
  Assets/HIS/Script/Citizen.cs.meta
  Assets/HIS/ScriptableObject.meta
  Assets/HIS/ScriptableObject/Data.meta
  Assets/HIS/ScriptableObject/Script.meta
  Assets/ObjectPool/Script/ObjectPoolManager.cs
  Assets/ObjectPool/Script/ObjectPoolManager.cs.meta
Labels: enhancement

#26 변수명 변경
  Assets/HIS/Script/Citizen.cs
Labels: bug

#29 변수 수정
  Assets/cms/Scripts/TimeManager.cs
  Assets/cms/Scripts/UIManager1.cs
  Assets/cms/pngwing.com.png.meta
Labels: bug

#31 BusId 선언 추가
  Assets/HIS/Script/Citizen.cs
Labels: bug

#37 스크립트 참조 수정
  Assets/HIS/Prefab/Citizen.prefab
  Assets/HIS/Prefab/Citizen.prefab.meta
  Assets/HIS/Scene.meta
  Assets/HIS/Scene/Test.unity
  Assets/HIS/Scene/Test.unity.meta
  Assets/HIS/Script/Citizen.cs
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/SampleScene.unity.meta
Labels: bug

#40 ui 수정
  Assets/cms/Scenes/SampleScene.unity
Labels: bug

#43 Enhancement/33
  Assets/JYS/Scripts/Bus.cs
  Assets/KMC/Prefebs/Button.prefab
  Assets/KMC/Prefebs/Station.prefab
  Assets/KMC/Scenes/BusRouteInfo.unity
  Assets/KMC/Scripts/BusRouteInfo.cs
  Assets/KMC/Scripts/BusRouteInfoButton.cs
  Assets/KMC/Scripts/Garage.cs
  Assets/KMC/Scripts/InventoryUIButton.cs
  Assets/KMC/Scripts/InventoryUIButton.cs.meta
  Assets/KMC/Scripts/Station.cs
  Assets/cms/Scenes/SampleScene.unity
  Assets/cms/Scripts/ResourceManager.cs
  Assets/cms/Scripts/UIManager2.cs
Labels: bug, enhancement

#49 Enhancement/48
  Assets/KMC/Scenes/BusRouteInfo.unity
  Assets/KMC/Scripts/BusRouteInfo.cs
  Assets/KMC/Scripts/Garage.cs
  Assets/KMC/Scripts/InventoryUIButton.cs
  Assets/KMC/Scripts/Station.cs
  Assets/cms/Scripts/UIManager2.cs
Labels: enhancement

#47 정류장 마우스 트랙 수정
  Assets/cms/Scenes/SampleScene.unity
  Assets/cms/Scripts/UIManager2.cs
Labels: bug

#54 fix(bus bug) and enhancement(jjw asset)
  Assets/HIS/Prefab/Citizen.prefab
  Assets/HIS/Script/Citizen.cs
  Assets/JJW/Image/KakaoTalk_20240814_002058269_01.png.meta
  Assets/JYS/Prefabs/Bus.prefab
  Assets/Node/Prefab/FactoryNode.prefab
  Assets/Node/Prefab/HomeNode.prefab
  Assets/Node/Prefab/ShopNode.prefab
  Assets/Node/Prefab/ShopNode.prefab.meta
  Assets/Scenes/IntegratedScene.unity
  Assets/cms/Scripts/UIManager2.cs
Labels: bug

#56 버스 요금 지불 추가
  Assets/HIS/Script/Citizen.cs
  Assets/JYS/Scripts/Bus.cs
Labels: enhancement

#58 라인 렌더러 수정
  Assets/KMC/Prefebs/Station.prefab
  Assets/Scenes/IntegratedScene.unity
Labels: bug

#59 feat(Station)
  Assets/KMC/Scripts/BusRouteInfo.cs
  Assets/KMC/Scripts/Station.cs
Labels: enhancement
